export const typeColours = {
  grass: "#dcfce7",
  poison: "#f3e8ff",
  fire: "#fed7aa",
  flying: "#e0f2fe",
  electric: "#fef3c7",
  water: "#dbeafe",
  bug: "#ecfccb",
  normal: "#dbdbdb",
  fairy: "#fce7f3",
  fighting: "#fee2e2",
  psychic: "#fae8ff",
  rock: "#dbdbc3",
  ghost: "#e0e7ff",
  ice: "#cffafe",
  dragon: "#ede9fe",
  dark: "#f4f4f5",
  steel: "#f1f5f9",
  ground: "#e0b03a",
};
